<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pick</string>
	</array>
	<key>name</key>
	<string>Pick Basic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((\;|^)\s{0,}\*).*|((\;|^)\s{0,}\!).*|\b(?i:REM)\b.*</string>
			<key>name</key>
			<string>comment.line.asterisk.pick</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.pick</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pick</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Program and Subroutine Highlighting</string>
			<key>match</key>
			<string>(?i:SUBROUTINE|PROGRAM) ([A-Za-z_-]+)</string>
			<key>name</key>
			<string>entity.name.function.pick</string>
		</dict>
		<dict>
		    <key>match</key>
		    <string>^([A-Za-z0-9_\.])+\:|^[0-9\.]+\b|;|,</string>
	   	    <key>name</key>
		    <string>entity.name.function.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\(.)+\\|\'(.)+\'|\"(.)+\")</string>
			<key>name</key>
			<string>string.other.quoted-or-unquoted.pick</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pick Clauses</string>
			<key>match</key>
			<string>\b(?i:CAPTURING|DO|END|ELSE|LOCKED|ONERR|ON ERROR|SETTING|THEN|UNTIL|WHILE)\b</string>
			<key>name</key>
			<string>keyword.other.pick</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pick Functions 1</string>
			<key>match</key>
			<string>\b(?i:@|ABS|ACCESS|ALPHA|ASCII|ASSIGNED|CHANGE|CHAR|COL1|COL2|CONVERT|COS|COUNT|DATE|DCOUNT|DELETE|DQUOTE|DTX|EBCDIC|EREPLACE|ERROR|EXCHANGE|EXP)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:EXTRACT|FIELD|FMT|FOLD|ICONV|INDEX|INMAT|INSERT|INT|LEN|LN|LOCATE|MAXIMUM|MINIMUM|MOD|NOT|NUM|OCCURS|OCONV|PWR|REM|REPLACE|RND|SCAN|SENTENCE)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:SEQ|SIN|SORT|SOUNDEX|SPACE|SQRT|SQUOTE|STATUS|STR|SUM|SUMMATION|SWAP|SYSTEM|TAN|TIME|TIMEDATE|TRIM|TRIMB|TRIMF|XTD)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\!|\#|&amp;|\*=|\+=|\\=|\^|-=|\/=|:|:=|&lt;=|&lt;&gt;|&gt;=|&gt;|&lt;|=|\+|-|\\|\/|\*)|\b(?i:AND|CAT|EQ|GE|GT|LE|LT|MATCH|NE|OR)\b)</string>
			<key>name</key>
			<string>keyword.operator.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ABORT|AUX|CASING|CLEAR|CLEARDATA|CLEARFILE|CLEARSELECT|COMPARE|CONVERT|CRT|DATA|DEL|DELETE|DIMENSION|ECHO|EQUATE|ERROR|FOOTING|GET|GETX|HEADING|IN|INPUT|INPUTCLEAR|INPUTCTRL|INPUTERR|INPUTNULL|INPUTPARITY|INS|KEY|LET|LOCATE|MAT|MATBUILD|MATPARSE|NULL|OUT|PAGE|PRECISION|PRINT ON|PRINTCHAR|PRINTER|PRINT|PROCREAD|PROCWRITE|PROMPT|REMOVE|REPLACE|REWIND|ROOT|RQM|SEND|SENDX|SPOOLQ|TA|TCL|TCLREAD)\b</string>
			<key>name</key>
			<string>support.function.pick</string>		
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:\$INCLUDE|\$OPTIONS|CFUNCTION|COMMON|INCLUDE)\b</string>
			<key>name</key>
			<string>support.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BEGIN CASE|BEGIN WORK|BREAK|COMMIT WORK|CONTINUE|DEBUG|END CASE|CASE|EXIT|FOR|GOSUB|GOTO|IF|IFR|INPUTTRAP OFF|INPUTTRAP|LOOP|NEXT|REPEAT|RETURN|ROLLBACK WORK|SLEEP|STOP|TO)\b</string>
			<key>name</key>
			<string>keyword.control.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:TRANSACTION|TRANSACTION ABORT|TRANSACTION CACHE|TRANSACTION COMMIT|TRANSACTION FLUSH|TRANSACTION ROLLBACK|TRANSACTION START)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
			<key>match</key>
			<string>\b(?i:\$CHAIN|CALL|CHAIN|ENTER|EXECUTE)\b</string>
			<key>name</key>
			<string>support.class.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:CLOSE|FILE|FILELOCK|FILEUNLOCK|FROM|LOCK|MATREAD|MATREADU|MATWRITE|MATWRITEU|ON|OPEN|RELEASE|READ|READNEXT|READT|READTX|READV|SELECT|UNLOCK|WEOF|WRITE|WRITET|WRITEU|WRITEV|WRITEVU|WRITEX)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pick</string>
	<key>uuid</key>
	<string>04e68b59-5469-4f66-aaf2-edeb0cfcb8bc</string>
</dict>
</plist>
