<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pick</string>
	</array>
	<key>name</key>
	<string>Pick Basic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((\;|^)\s{0,}\*).*|((\;|^)\s{0,}\!).*|\b(?i:REM)\b.*</string>
			<key>name</key>
			<string>comment.line.asterisk.pick</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.pick</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pick</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Program and Subroutine Highlighting</string>
			<key>match</key>
			<string>(?i:SUBROUTINE|PROGRAM) ([A-Za-z_-]+)</string>
			<key>name</key>
			<string>entity.name.function.pick</string>
		</dict>
		<dict>
		    <key>match</key>
		    <string>^([A-Za-z0-9_\.])+\:|^[0-9\.]+\b|;|,</string>
	   	    <key>name</key>
		    <string>entity.name.function.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\(.)+\\|\'(.)+\'|\"(.)+\")</string>
			<key>name</key>
			<string>string.other.quoted-or-unquoted.pick</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pick Clauses</string>
			<key>match</key>
			<string>\b(?i:CAPTURING|DO|END|ELSE|LOCKED|ONERR|ON ERROR|SETTING|THEN|UNTIL|WHILE)\b</string>
			<key>name</key>
			<string>keyword.other.pick</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pick Functions 1</string>
			<key>match</key>
			<string>\b(?i:@|ABS|ABSS|ADDS|ACCESS|ALPHA|ANDS|ASCII|ASSIGNED|BEFORE|BITCHANGE|BITCHECK|BITRESET|BITSETBYTELEN|CHANGE|CHAR|CHARS|CHDIR|CHECKSUM|COL1|COL2|CONVERT|CONVERTCOS|COS|COUNT|COUNTS|CREATE|DATE|DCOUNT|DECRYPT|DEFC|DEFCE|DEFFUN|DOWNCASE|DQUOTE|DROUND|DTX|DYNTOXMLEBCDIC|EBCDIC|ENCRYPT|EREPLACE|ERROR|EXCHANGE|EXP)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:EXTRACT|FIELD|FIELDS|FMT|FMTS|FOLD|GETCWD|GETENV|GETLIST|ICONV|ICONVS|INDEX|INMAT|INSERT|INT|ISALNUMISDIGIT|ISALPHA|ISCNTRL|ISLOWER|ISPRINT|ISSPACE|ISUPPER|ITYPE|JBASECOREDUMP|JBASETHREADCreate|JBASETHREADStatus|JQLEXECUTE|JQLFETCH|JQLGETPROPERTY|JQLPUTPROPERTY|LATIN1|LEFT|LEN|LENDP|LENS|LN|LOCALDATE|LOCALTIM|LOCATE|LOWCASE|LOWER|MAKETIMESTAMP|MAXIMUM|MINIMUM|MOD|MODS|NOT|NUM|OCCURS|OCONV|OCONVS|PWR|REM|REPLACE|RND|SCAN|SENTENCE)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:SEQ|SEQS|SIN|SORT|SOUNDEX|SPACE|SPACES|SQRT|SQUOTE|STATUS|STR|SUM|SUMMATION|SWAP|SYSTEM|TAN|TIME|TIMEDATE|TIMEDIFF|TIMEOUT|TIMESTAMP|TRIM|TRIMB|TRIMBS|TRIMF|TRIMFS|XTD)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\!|\#|&amp;|\*=|\+=|\\=|\^|-=|\/=|:|:=|&lt;=|&lt;&gt;|&gt;=|&gt;|&lt;|=|\+|-|\\|\/|\*)|\b(?i:AND|CAT|DIV|DIVD|DIVS|EQ|EQU|EQS|GE|GES|GT|LE|LES|LT|MATCH|MATCHFIELD|NE|NEGS|NES|OR|SMUL)\b)</string>
			<key>name</key>
			<string>keyword.operator.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ABORT|AUX|CASING|CATS|CHANGETIMESTAMP|CLEAR|CLEARDATA|CLEARFILE|CLEARINPUT|CLEARSELECT|COMPARE|CONVERT|CRT|DATA|DEL|DELETE|ECHO|EQUATE|ERROR|FIND|FINDSTR|FLUSH|FOOTING|FORMAT|FORMLIST|FUNCTION|GET|GETX|GETUSERGROUP|HEADING|HEADINGE|HEADINGN|HUSH|IN|INPUT|INPUTCLEAR|INPUTCTRL|INPUTERR|INPUTNULL|INPUTPARITY|INS|KEY|KEYIN|LET|LOCATE|MAT|MATBUILD|MATPARSE|NULL|OUT|PAGE|PRECISION|PRINT ON|PRINTCHAR|PRINTER|PRINT|PROCREAD|PROCWRITE|PROMPT|REMOVE|REPLACE|REWIND|ROOT|RQM|SEND|SENDX|SPOOLQ|TA|TCL|TCLREAD)\b</string>
			<key>name</key>
			<string>support.function.pick</string>		
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:\$INCLUDE|\$OPTIONS|CFUNCTION|CLEARCOMMON|COMMON|COLLECTDATA|DIM|DIMENSION|INCLUDE)\b</string>
			<key>name</key>
			<string>support.type.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BEGIN CASE|BEGIN WORK|BREAK|COMMIT WORK|CONTINUE|DEBUG|END CASE|CASE|EXIT|FOR|GO|GOSUB|GOTO|GROUP|IF|IFR|IFS|INPUTTRAP OFF|INPUTTRAP|LOOP|NEXT|REPEAT|RETURN|ROLLBACK WORK|SLEEP|STOP|TO)\b</string>
			<key>name</key>
			<string>keyword.control.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:TRANSACTION|TRANSACTION ABORT|TRANSACTION CACHE|TRANSACTION COMMIT|TRANSACTION FLUSH|TRANSACTION ROLLBACK|TRANSACTION START)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
			<key>match</key>
			<string>\b(?i:\$CHAIN|CALL|CALLC|CALLDOTNET|CALLJ|CALLONEXIT|CHAIN|ENTER|EXECUTE)\b</string>
			<key>name</key>
			<string>support.class.pick</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:CLOSE|CLOSESEQ|DELETELIST|DELETESEQ|DELETEU|FILE|FILEINFO|FILELOCK|FILEUNLOCK|FROM|GETLIST|LOCK|MATREAD|MATREADU|MATWRITE|MATWRITEU|ON|OPEN|RELEASE|READ|READNEXT|READT|READTX|READV|SELECT|UNLOCK|WEOF|WRITE|WRITET|WRITEU|WRITEV|WRITEVU|WRITEX)\b</string>
			<key>name</key>
			<string>storage.type.pick</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pick</string>
	<key>uuid</key>
	<string>04e68b59-5469-4f66-aaf2-edeb0cfcb8bc</string>
</dict>
</plist>
